#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct.

CHROME_VERSION=$(curl -sSL 'http://omahaproxy.appspot.com/all?csv=1' | grep linux,stable | cut -d ',' -f 3)
echo "Chrome: $CHROME_VERSION"

docker build \
  --build-arg CHROME_VERSION=$CHROME_VERSION \
  -t $IMAGE_NAME .
